// <auto-generated />
using System;
using MauroSalguero_1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MauroSalguero_1P.Migrations
{
    [DbContext(typeof(MauroSalguero_1PContext))]
    [Migration("20231025125028_CambiosBdd")]
    partial class CambiosBdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MauroSalguero_1P.Models.MauroSalguero_tabla", b =>
                {
                    b.Property<string>("msName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("msDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("msEdad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("msGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("msID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("msUdlaStudent")
                        .HasColumnType("bit");

                    b.HasKey("msName");

                    b.ToTable("MauroSalguero_tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
